region: "us-east-1"
sg_id: "sg-0e3e5d0160ba94b0b"
image_id: "ami-0220d79f3f480ecf5"
instance_type: "t3.micro"
env: "dev"
instances:
  - "mongodb"
  - "catalogue"
zone_name: "rkak87.online"
action: "create"
common_tags:
  owner: ansible
  project: roboshop
  environment: "{{ env }}"